feat: добавлен вывод числовых инпутов в props-editor
colibrijs/colibrijs pull request #103
Opened 2024-06-24 22:59 UTC by okovtkov

Resolve #98 

Есть подозрение, что изменять прошлые тесты не самая лучшая идея, но раз уж у нас будут теститься пропсы с разными типами, то лишний повторяющийся тип-строку убрал

2024-06-25 04:43 UTC, ivan-podgornov requested changes

2024-06-25 04:43 UTC, ivan-podgornov commented on packages/core/components/props-editor/props-editor.tsx
> +    return schema.properties[propName]?.type || 'string'; // прокомментируй это. Не даёт мне без вопросика писать
ну типа propName может быть, а может и не быть в properties. Вроде тут всё логично. Тут надо чуть по-другому проверять, надо type guard писать в пакете со схемами:

isPropertyNumber: (property: Property<SchemaValues>) => property is Property<number>;
isPropertyString: (property: Property<SchemaValues>) => property is Property<string>;

2024-06-25 04:43 UTC, ivan-podgornov commented on packages/core/components/props-editor/props-editor.tsx
>            <Input
Давай всё что касается редактирования конкретного пропса, вынесем в отдельный компонент prop-editor. Ну и там сделаем ещё отдельные компоненты string-editor, number-editor. В будущем будет ещё boolean-editor, array-editor, object-editor и т.д.

Тестами тоже лучше покрыть отдельно каждый тип данных. Если всё пойдёт хорошо, то у разных типов данных будут свои настроки. Для чисел - это может быть например: только целые числа или максимум-минимум.

У строк тоже может быть максимум-минимум, но тут уже будет иметься в виду длина строки. В общем отдельные типы могут совсем по-разному работать и их лучше разбивать на отдельные компоненты.

2024-06-26 18:58 UTC, ivan-podgornov commented on packages/core/components/props-editor/props-editor.tsx
> +    return schema.properties[propName]?.type || 'string'; // прокомментируй это. Не даёт мне без вопросика писать
Посмотрели и оказалось что то что выше не нужно

2024-07-02 19:55 UTC, ivan-podgornov requested changes

2024-07-02 19:55 UTC, ivan-podgornov commented on packages/core/components/prop-editor/types/number-editor.tsx
> +      <label className="number-editor__label" htmlFor={name}>
у [FormItem](https://ant.design/components/form#formitem) есть проп label. Давай использовать его и тогда не придётся даже связывать label с инпутом. Всё заработает за счёт того что Input будет внутри label. Предлагаю название поля выводить в этом пропсе label, а то что указано в description в пропсе help

Ещё на этом проекте нет бэм, тут css-модули. Если нужно какой-то стиль задать, просто файлик css импортируешь, да ото и всё

2024-07-02 19:55 UTC, ivan-podgornov commented on packages/core/components/prop-editor/types/number-editor.tsx
> +      <Input
В antd для чисел есть [InputNumber](https://ant.design/components/input-number). Давай это использовать

2024-07-02 19:55 UTC, ivan-podgornov commented on packages/core/components/prop-editor/types/string-editor.tsx
> +export interface Props {
Пропсы повторяются от компонента к компоненту. Видимо то что здесь указано - это база. Давай вынесем пропсы в отдельный тип BaseEditorProps:

```
interface BaseProps<T extends SchemaValues> {
  /* Имя инпута */
  name: string;

  /** Редактируемое свойство */
  property: Property<T>;

  /** Значение по умолчанию */
  value: T;

  /** Функция, которая будет вызвана, когда пропсы поменяются */
  onChange: (value: T) => void;
}
```

Дальше в StringEditor можно будет написать `type StringEditorProps = BaseProps<string>`, ну а в NumberEditor - `type NumberEditorProps = BaseProps<number>`;

2024-07-02 19:55 UTC, ivan-podgornov commented on packages/core/components/prop-editor/types/string-editor.tsx
> +      <label className="string-editor__label" htmlFor={name}>
тут то же самое про label и help

2024-07-02 19:55 UTC, ivan-podgornov commented on packages/core/components/props-editor/props-editor.tsx
> +      (newValue: SchemaValues) => {
в newValue получается приходит тип T[K], а не SchemaValues. Или тогда тс агрессию проявляет?

2024-07-02 19:55 UTC, ivan-podgornov commented on packages/core/components/props-editor/props-editor.tsx
> +          property={getProperty(propName)}
так и не понял зачем отдельные функции getProperty и getValue. Но если надо, пусть будет

2024-07-02 19:55 UTC, ivan-podgornov commented on packages/schema/type-guards.ts
> +function isPropertyString(property: Property<SchemaValues>): property is Property<string> {
давай удолим весь файлик раз уж оно не используется.

2024-07-02 22:16 UTC, okovtkov commented on packages/core/components/prop-editor/types/string-editor.tsx
> +export interface Props {
https://www.youtube.com/watch?v=ejNGCWEgJNU&ab_channel=Dozenazer[https://www.youtube.com/watch?v=ejNGCWEgJNU&ab_channel=Dozenazer](url)

2024-07-02 22:40 UTC, okovtkov commented on packages/core/components/props-editor/props-editor.tsx
> +          property={getProperty(propName)}
![image](https://github.com/colibrijs/colibrijs/assets/66257346/2e8452ad-476e-457a-bd9e-8765a807c1ad)
вот это замахало, пришел только к подобному

2024-07-02 22:43 UTC, okovtkov commented on packages/core/components/props-editor/props-editor.tsx
> +      (newValue: SchemaValues) => {
![image](https://github.com/colibrijs/colibrijs/assets/66257346/84617a15-4f55-4a16-894f-229785acf7fe)

2024-07-02 22:55 UTC, ivan-podgornov requested changes

2024-07-02 22:55 UTC, ivan-podgornov commented on packages/core/components/prop-editor/prop-editor.tsx
> +}
Тут тоже можно использовать BaseProps - `BaseProps<SchemaValues>`

2024-07-02 22:57 UTC, ivan-podgornov commented on packages/schema/type-guards.ts
> +function isPropertyString(property: Property<SchemaValues>): property is Property<string> {
https://github.com/colibrijs/colibrijs/blob/issue-98/packages/schema/index.ts#L3

2024-07-06 21:04 UTC, ivan-podgornov requested changes

2024-07-06 21:04 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/number-editor.spec.stories.tsx
> +    value: 228,
тут и в других тестах. Не нужно указывать весь набор пропсов. Указывай только те что имеют отношение к тесту. Остальные с export default. Здесь, например, достаточно указать только value

2024-07-06 21:04 UTC, ivan-podgornov commented on packages/core/components/prop-editor/test-object.ts
> +  getElement(propEditorTestId: string, elementType: 'input' | 'label' | 'description') {
такой test object не особо полезен. По-идее, test object должен абстрагировать от реализации. Вот у тебя тут input, label и description. Description ещё ок, он относится к property. Но вот то что label и input фигурируют не круто. Всем пользователям prop-editor должно быть всё равно как под капотом устроен prop-editor. Они должны иметь возможность получить название пропса, его описание и значение. То есть, должны быть методы:

```ts
getPropertyName: () => string;
getPropertyDescription: () => string;
getValue: () => string;
setValue: (value: string) => Promise<void>;
```

Ещё сейчас во всех возвращаемых типах я указал string. Но допустимо возвращать Element. Так тоже норм.

Так же testId лучше указывать в конструкторе, а не в методе

2024-07-06 21:04 UTC, ivan-podgornov commented on packages/core/components/props-editor/__stories__/common.test.stories.tsx
> +export const TypeAttributes: Story = {
вот это если и проверять, то в prop-editor, а не здесь

2024-07-06 21:04 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/number-editor.spec.stories.tsx
> +    const numberEditor = getByTestId('prop-editor__input');
тут и в других местах давай использовать test object

2024-07-06 21:04 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/number-editor.spec.stories.tsx
> +      expect(NumberEditorChange.args?.onChange).toHaveBeenCalledWith(227);
args прилетают в аргументах play функции. Бери их оттуда, а не из NumberEditorChange. В других местах то же самое

2024-07-06 21:04 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/string-editor.spec.stories.tsx
> +      expect(stringEditor).toHaveValue('Valueff');
тут можно поменять на `expect(stringEditor).toHaveValue(args.value)`, это не обязательно, это для общего развития

2024-07-06 21:04 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/string-editor.spec.stories.tsx
> +  name: 'Вызывается onChange при вводе в инпут в string-editor',
"вызывается onChange с введённым значением при вводе в инпут в string-editor" - важно уточнить что не просто по приколу callback вызывается

2024-07-07 16:20 UTC, ivan-podgornov approved these changes

2024-07-07 16:26 UTC, merged