feat: создана getDefaultValues функция
colibrijs/colibrijs pull request #111
Opened 2024-07-11 19:19 UTC by okovtkov

Resolve #84

2024-07-12 20:26 UTC, ivan-podgornov requested changes

2024-07-12 20:26 UTC, ivan-podgornov commented on packages/schema/utils/get-default-values.ts
> +export function getDefaultValues<T extends Record<string, SchemaValues>>(schema: JsonSchema<T>): T {
нет тестов, нужны юнит-тесты

2024-07-12 20:26 UTC, ivan-podgornov commented on packages/schema/utils/get-default-values.ts
> +  return defaultValues as T;
Если упороться, кажется можно обойтись без as. Но это не точно

2024-07-13 09:41 UTC, okovtkov commented on packages/schema/utils/get-default-values.ts
> +  return defaultValues as T;
без ass

2024-07-14 11:15 UTC, ivan-podgornov approved these changes

2024-07-14 11:16 UTC, merged