feat: добавлена поддержка объектов в prop-editor
colibrijs/colibrijs pull request #114
Opened 2024-07-21 15:36 UTC by okovtkov

Resolve #112

2024-07-22 19:07 UTC, ivan-podgornov requested changes

2024-07-22 19:07 UTC, ivan-podgornov commented on packages/core/components/prop-editor/components/layout.module.css
назови файлик object-editor.module.css, чтобы сразу было видно к чему он относится

2024-07-22 19:07 UTC, ivan-podgornov commented on packages/core/components/prop-editor/prop-editor.tsx
> +  type PrimitiveType = string | number | boolean;
типок уже имеется в `@colibrijs/schema`

2024-07-22 19:07 UTC, ivan-podgornov commented on packages/schema/types.ts
> +export type SchemaValues = string | number | boolean | object;
SchemaValues лучше под PrimitiveType объявить:

```
export type SchemaValues =  PrimitiveType | object;
```

2024-07-22 19:07 UTC, ivan-podgornov commented on packages/core/components/prop-editor/components/object-editor.tsx
> +  const properties = Object.keys(property.properties) as (keyof T)[];
заюзай тут getPropertiesNames(). Только в этой функции нужно будет возвращаемый тип тоже указать `(keyof T)[]`

2024-07-22 19:07 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/object-editor.spec.stories.tsx
> +    },
вот этот property не нужен для этого теста. Давай какой-то один жирный объект зададим в export default args, а в тестах будем указывать только то что нужно для теста

2024-07-22 19:07 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/object-editor.spec.stories.tsx
> +    const name = objectEditor.getObjectName();
а зачем тут отдельный TO? В обычном TO, есть getPropertyName

2024-07-22 20:44 UTC, okovtkov commented on packages/core/components/prop-editor/prop-editor.tsx
> +  type PrimitiveType = string | number | boolean;
это я тебя так проверял

2024-07-22 20:48 UTC, okovtkov commented on packages/core/components/prop-editor/components/object-editor.tsx
> +  const properties = Object.keys(property.properties) as (keyof T)[];
getPropertiesNames принимает схему в себя, а тут ее нет

2024-07-26 21:22 UTC, ivan-podgornov requested changes

2024-07-26 21:22 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/primitive-editor.spec.stories.tsx
> +  name: 'При передаче типа number в property, отрисовуется number-editor',
это нет особого смысла проверять. Главное что компонент prop-editor правильно ведёт себя - это проверяется в других тестах. А какой из эдиторов отрисовывается, не важно. Это типа подход BDD предполагает, что тестируем поведение, а не внутренности

2024-07-26 21:22 UTC, ivan-podgornov commented on packages/core/components/prop-editor/test-object.ts
> +    return await new Promise((resolve) => resolve(null));
@storybook/test экспортирует функцию waitFor(). Давай использовать её и явно указывать какой элемент ожидаем увидеть. Например, если нужно подождать появление какой-либо модалки, можно использовать такой код:

```ts
async waitForModal() {
  await waitFor(() => expect(container.getByTestId('element')));
}
```

2024-07-26 21:22 UTC, ivan-podgornov commented on packages/core/components/props-editor/__stories__/props-editor.stories.tsx
> +export type Story = StoryObj<typeof PropsEditor<Record<string, SchemaValues>>>;
тут лучше не Record<string, SchemaValue> а просто object

2024-07-26 21:22 UTC, ivan-podgornov commented on packages/schema/utils/get-default-values.ts
> +  const keys = Object.keys(properties);
вот тут используется Object.keys(properties), хотя уже есть функция getPropertiesNames(); Лучше использовать её. Тут все функции принимают T extends Record<string, SchemaValues>, можно по-идее оставить просто T. Ну или хотя бы T extends object оставить

2024-07-26 21:22 UTC, ivan-podgornov commented on packages/schema/utils/get-default-values.ts
> -  const keys = Object.keys(schema.properties);
Реализация поменялась, а тесты нет. Подозрительно

2024-07-26 21:24 UTC, ivan-podgornov requested changes

2024-07-26 21:24 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/object-editor.spec.stories.tsx
> +    expect(additionalInformationName).toHaveTextContent('additionalInformation');
не хватает стэпов в тестах и ещё вторым параметром можно указать текст обозначающий что именно ты проверяешь

2024-07-26 21:33 UTC, okovtkov commented on packages/core/components/props-editor/__stories__/props-editor.stories.tsx
> +export type Story = StoryObj<typeof PropsEditor<Record<string, SchemaValues>>>;
![image](https://github.com/user-attachments/assets/a78b3a57-ce37-4413-bbb6-7e9692b9d964)

2024-07-26 21:47 UTC, ivan-podgornov commented on packages/core/components/props-editor/__stories__/props-editor.stories.tsx
> +export type Story = StoryObj<typeof PropsEditor<Record<string, SchemaValues>>>;
Ну потому что Default принимает тоже Record<string, SchemaValues>. Надо там тоже убрать и на 12 строке у тебя на скрине

2024-07-28 12:41 UTC, okovtkov commented on packages/schema/utils/get-default-values.ts
> -  const keys = Object.keys(schema.properties);
А что менять, если работает так же?

2024-07-28 13:09 UTC, okovtkov commented on packages/schema/utils/get-default-values.ts
> -  const keys = Object.keys(schema.properties);
а, обжект добавился

2024-07-30 18:47 UTC, ivan-podgornov requested changes

2024-07-30 18:47 UTC, ivan-podgornov commented on packages/core/components/prop-editor/__stories__/object-editor.spec.stories.tsx
> +    step('Проверяем, что именование объекта равно пропсу name', () => {
давай второй параметр expect использовать, а не step

2024-07-30 18:47 UTC, ivan-podgornov commented on packages/core/components/prop-editor/test-object.ts
> +  async toggleSwitcher(step: StepFn) {
передавать step в параметрах метода такое себе. Давай передавать в параметрах конструктора, как это делается в остальных местах

2024-07-30 22:09 UTC, ivan-podgornov approved these changes

2024-07-30 22:09 UTC, merged