feat: создан компонент element-editor
colibrijs/colibrijs pull request #118
Opened 2024-09-22 16:44 UTC by okovtkov

2024-09-22 17:06 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +              danger
danger тут нужно убрать

2024-09-22 17:06 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +    return JSON.stringify(startProps) !== JSON.stringify(element.props);
Допустим был объект у которого есть поле title равное "Заголовок". Я пишу "Заголовок 123", сохраняю, потом хочу поменять назад на "Заголовок" и всё - добрый вечер, ничего не получается

2024-09-22 17:06 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +        alert('Ты за баазром-то следи');
хочется получать эту ошибку, когда ввожу невалидный JSON. Но сейчас буду получать, если передам функцию onEdit, которая по какой-то причине выбрасывает ошибку

2024-09-22 17:06 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +      open={Boolean(element)}
судя по типам пропсов element есть всегда. Давай добавим пропсы open и onClose, чтобы было что сюда передавать

2024-09-22 17:06 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +      title={<span data-testid="element-editor-drawer__title">{element?.component.name}</span>}
И вот тут непонятно откуда взялся `?.`, если element есть всегда

2024-09-22 17:06 UTC, ivan-podgornov commented on packages/core/components/element-editor/__stories__/element-editor.stories.tsx
> +      const elementClone = structuredClone(elementExample);
зачем тут делать структурного клона? Можно просто сделать `setElementExample({ ...elementExample, props })`

2024-09-22 17:06 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +  const [startProps] = useState(structuredClone(element.props));
тут тоже непонятно зачем хранить структурного клона. Кажется можно хранить результат выполнения JSON.stringify над element.props

2024-09-23 14:50 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +  const [startProps, setStartProps] = useState(JSON.stringify(element.props));
давай назовём lastSavedProps

2024-09-23 14:50 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +      {element && (
Почему элемент проверяется? Он же всегда есть. Не понимаю немного)

2024-09-23 14:51 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +        alert('Ты за баазром-то следи');
тут ничего не изменилось. Ну да и пофиг, всё равно в перспективе будет props-editor использоваться. Пусть так будет

2024-09-23 14:56 UTC, okovtkov commented on packages/core/components/element-editor/element-editor.tsx
> +      {element && (
Да, это тоже ошибка. Копипаст прошлого кода повлиял

2024-09-27 22:16 UTC, ivan-podgornov requested changes

2024-09-27 22:16 UTC, ivan-podgornov commented on packages/core/components/element-editor/__stories__/common.spec.stories.tsx
> +      fireEvent.input(textarea, { target: { value: '{\n "title": "Заголовок1"\n}' } });
а почему тут fireEvent, а не userEvent? На то были причины или просто так случай распорядился?

2024-09-27 22:16 UTC, ivan-podgornov commented on packages/core/components/element-editor/__stories__/common.spec.stories.tsx
> +    step('Убедимся, что галчонок отныне виден', () => {
тут и в других местах. Указывай в expect'ах то что проверяешь, не в степах. Expect второй параметр принимает с описанием

2024-09-27 22:16 UTC, ivan-podgornov commented on packages/core/components/element-editor/__stories__/common.spec.stories.tsx
> +  args: { isOpen: true, element: { ...exampleElement } },
зачем тут делать копию элемента? Переживаешь что кто-то его мутирует по пути? Не переживай за это, всё будет хорошо

2024-09-27 22:16 UTC, ivan-podgornov commented on packages/core/components/element-editor/element-editor.tsx
> +  isOpen: boolean;
Вот тут кажется не очень, что пропс isOpen называется. В других местах просто open. Давай переименуем

2024-09-27 22:39 UTC, okovtkov commented on packages/core/components/element-editor/__stories__/common.spec.stories.tsx
> +      fireEvent.input(textarea, { target: { value: '{\n "title": "Заголовок1"\n}' } });
LuserEvent будет продолжать вводить что-то в уже готовую строку. То есть там изначально джсон объект наш, и после "}" символа он будет что-то вписывать, а это невалидная строка, алерт вылетит и всё такое. Быть может можно как-то задать на каком по счету символе писать надо, но я пришел к тому, что проще fireEvent заюзать)

2024-09-27 22:54 UTC, ivan-podgornov approved these changes

2024-09-27 22:55 UTC, ivan-podgornov approved these changes

2024-09-27 23:02 UTC, merged