feat: добавление в сторибук информации об упавших сторисах
colibrijs/colibrijs pull request #151
Opened 2024-10-22 12:10 UTC by okovtkov

2024-10-22 16:03 UTC, ivan-podgornov requested changes

2024-10-22 16:03 UTC, ivan-podgornov commented on packages/core/.storybook/main.ts
> +  stories: ['../components/page-title/__stories__/screenshot/*.stories.@(ts|tsx)'],
Вот это изменение убери

2024-10-22 16:03 UTC, ivan-podgornov commented on packages/core/components/page-title/page-title.tsx
> +    <Flex align="baseline" justify="flex-start" data-testid="page-title">
И это

2024-10-22 16:05 UTC, ivan-podgornov requested changes

2024-10-22 16:05 UTC, ivan-podgornov commented on .github/workflows/pull-request.yml
> +          if [ "${{ steps.run_test.outcome }}" = "failure" ]; then
If лучше выше для теста написать. Рядом с run. Тогда и run попроще будет для восприятия

2024-10-25 16:15 UTC, ivan-podgornov requested changes

2024-10-25 16:15 UTC, ivan-podgornov commented on .github/workflows/pull-request.yml
> +      # - deploy-example
тут убери комент

2024-10-25 16:15 UTC, ivan-podgornov commented on .github/workflows/pull-request.yml
> +    continue-on-error: true
эту штуку тоже убери. Сейчас если юниты или е2е упадут, все проверки пройдут, хотя не должны. Чтобы запустился деплой, несмотря на падение этой джобы, добавь там:

```
if: always()
```

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions

2024-10-25 16:15 UTC, ivan-podgornov commented on packages/core/components/page-title/__stories__/page-title.stories.ts
> +  },
А это что за покемон?)

2024-10-25 16:15 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +const ADDON_ID = 'storybook/screenshots';
укажи тут лучше @colibrijs/screenshots

2024-10-25 16:15 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +function ScreenshotsPanel({ active, api }: ScreenshotsPanelProps): ReactElement | null {
Возвращаемый тип лучше указать как ReactNode.

2024-10-25 16:15 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +      <p className="screenshot-panel__text">Здесь ты можешь наблюдать список упавших тестов: </p>
А можешь и не наблюдать. Их-то может и не быть упавших. А сделай чтоб какой-то тест заруинился. Ничего страшного, что сломается компонент из-за этого. Пусть ломается

2024-10-25 16:15 UTC, ivan-podgornov commented on .github/workflows/pull-request.yml
> +        if: ${{ steps.run_test.outcome != 'success' }}
тут фигурные скобки с долларом не обязательно указывать. Но и комент этот необязательно было писать

2024-10-25 16:15 UTC, ivan-podgornov commented on packages/core/package.json
> +    "@storybook/api": "^7.0.12",
не используется и версия слишком стара

2024-10-26 07:14 UTC, ivan-podgornov requested changes

2024-10-26 07:14 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +function kebabize(str: string) {
![2a895dda1d106e4c55f15ed5fb97e5a4](https://github.com/user-attachments/assets/75e1a15c-f072-40f4-a0a5-21687a2c4dfa)

2024-10-26 07:14 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +function ScreenshotsPanel({ active, api }: ScreenshotsPanelProps): ReactNode | null {
ReactNode включает у себя null

2024-10-26 07:14 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +        setStories(storiesData.flat());
.map.flat можно заменить на flatMap. Но можно и так оставить

2024-10-26 07:14 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +      <p className="screenshot-panel__text">Здесь ты можешь наблюдать список упавших тестов: </p>
Ну прекол конечно тот ещё. Я почему-то вчера подумал что ci не сломается из-за скриншота. Белка наверное. Верни пожалуйста скриншоты в чувство

2024-10-26 07:20 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +      <p className="screenshot-panel__text">Здесь ты можешь наблюдать список упавших тестов: </p>
Ну зато я увидел что не работает в ci то что ты сделал, потому что для fetch абсолютный путь указывается, а не относительный. Желательно, чтоб была какая-то обработка ошибок на запросы к report.json и как-то нужно обработать ситуацию, когда всё хорошо и упавших скриншотов нет.

2024-10-26 10:16 UTC, okovtkov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +function kebabize(str: string) {
![Uploading Studio-Session-33791-Edit-copy-1-scaled-e1687370058284.jpg…]()

2024-10-26 17:46 UTC, okovtkov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +function kebabize(str: string) {
![image](https://github.com/user-attachments/assets/e70948b0-36ee-4510-9aee-4a1228fdd80a)

2024-10-26 17:50 UTC, okovtkov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +      <p className="screenshot-panel__text">Здесь ты можешь наблюдать список упавших тестов: </p>
По поводу последнего, то просто пустота будет во вкладке. Там где return null делается, там в if поместил stories.length

2024-10-27 13:47 UTC, ivan-podgornov requested changes

2024-10-27 13:47 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +      <p className="screenshot-panel__text">Здесь ты можешь наблюдать список упавших тестов: </p>
Что про ошибку, что про отсутствие упавших тестов можно вменяемую информацию вывести? На случай отсутствия падений можно вывести "Все скриншотные тесты прошли успешно. Всё хорошо". На случай ошибки информацию про то как запустить скриншотные тесты локально, чтобы появилась какая-то информация

2024-10-27 17:00 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +      <p className="screenshot-panel__text">Здесь ты можешь наблюдать список упавших тестов: </p>
Итого что нужно сделать:

- Когда есть упавшие скриншотные тесты, их нужно выводить с более понятным названием. Например: "ComponentRemove/tests/api/RequestError"
- Когда всё прошло хорошо, вместо белого экрана выводить: "Все скриншотные тесты прошли успешно".
- Обработку ошибок в отдельное issue выносим

2024-10-27 19:12 UTC, ivan-podgornov approved these changes

2024-10-27 19:13 UTC, merged