feat: по запросу на ревью, добавлен вывод сообщение в телеграм
colibrijs/colibrijs pull request #153
Opened 2024-10-23 13:24 UTC by baronin

2024-10-23 13:25 UTC, baronin reviewed
test

2024-10-23 13:38 UTC, baronin reviewed
start

2024-10-24 14:29 UTC, ivan-podgornov requested changes

2024-10-24 14:29 UTC, ivan-podgornov commented on .github/workflows/pull-request.yml
> +    if: github.event.action == 'review_requested'
давай вот эту джобу вынесем в файлик pull-request-review, которая будет запускаться при:

```
on:
  pull-request:
    - review_requested
```

2024-10-24 14:29 UTC, ivan-podgornov commented on .github/workflows/pull-request-review.yml
> +      - name: Send message to Telegram
то что касатеся просмотра ревью, давай пока что выпилим. Хочу чтоб в итоге бот слал в комментарии к одному сообщению всё что касается пулл реквеста

2024-10-24 14:29 UTC, ivan-podgornov commented on .github/workflows/pull-request.yml
> +          for reviewer in $reviewers; do
bash это конечно прикольно, но давай следующим issue на ts это перепишем. Назовём пакет @colibrijs/control-freak и туда всё это вынесем. Нужно будет сделать, чтобы мы в run писали:

```bash
# и т.д.
control-freak --action=request-review --reviewers=$REQUESTED_REVIEWERS --actor=${{ github-actor }}
```

2024-10-24 14:49 UTC, ivan-podgornov approved these changes

2024-10-24 14:49 UTC, merged