feat: добавлена команда для обновления сторисов репорта
colibrijs/colibrijs pull request #161
Opened 2024-11-02 21:12 UTC by okovtkov

Resolve #160

2024-11-02 21:13 UTC, okovtkov commented on packages/core/.storybook/screenshot-panel/get-report-data.ts
> +}
Изначально задумывалось, что это будет в нескольких местах юзаться.
Но тут прям такой код, что пусть наверное лучше так и будет

2024-11-02 21:52 UTC, ivan-podgornov requested changes

2024-11-02 21:52 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-approve/cli.ts
> +});
Интересно, знаешь ли ты что ниже то же самое?

```ts
commander.command('screenshot-approve').action(screenshotApprove);
```

Это не призыв к действию, просто вопрос. Ещё интересно как относишься к такой записи

2024-11-02 21:52 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/get-report-data.ts
> +}
Тут указано что функция возвращает некий объект, который является одновременно и репортом и ошибкой. Ты имел в виду оператор `|`, а не `&`. Но даже так было бы неправильно. Функция не возвращает ошибку, а выбрасывает её, поэтому это указывать не надо в возвращаемом типе.

Ну и убери слово Data везде. Выглядит как слово-паразит

2024-11-02 21:52 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/types.ts
>  export type ReportData = {
Тут тоже слово Data убери несмотря на то что придётся задеть файлы которые к пр не относятся

2024-11-02 21:52 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-approve/screenshot-approve.ts
> +  const parsedData: ReportData = JSON.parse(jsonData);
блин и тут везде data :-)

2024-11-02 23:01 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-approve/cli.ts
> +});
Так а относишься-то как?

2024-11-02 23:42 UTC, okovtkov commented on packages/core/.storybook/screenshot-approve/cli.ts
> +});
Понимаю ее. Просто копировал контрол-фрик, и вставил своё, особо не обратив внимание на это

2024-11-05 20:08 UTC, ivan-podgornov commented
Комментарий

2024-11-07 19:20 UTC, ivan-podgornov submitted a review, later dismissed

2024-11-07 22:35 UTC, merged