feat(ci): реализован ответ на ревью в CI
colibrijs/colibrijs pull request #162
Opened 2024-11-08 12:18 UTC by baronin

Resolve #158

2024-11-08 12:19 UTC, baronin reviewed
что ты тут понаписывал але

2024-11-08 12:50 UTC, baronin reviewed
все фигня, давай по новой

2024-11-08 13:49 UTC, ivan-podgornov requested changes

2024-11-08 13:49 UTC, ivan-podgornov commented on packages/control-freak/interfaces.ts
> +export interface Options {
Давай файлик назовём types.ts. Как-то непривычно, что interfaces используется. Это всё субъективная история. Объективных причин так делать нет. Давай так же назовём интерфейс не Options, а ReviewOptions, чтоб не обезличено было

2024-11-08 13:49 UTC, ivan-podgornov commented on packages/control-freak/request-review.ts
> +  const params = new URLSearchParams({
раз уж появилась функция sendTelegramRequest, давай там то же URLSearchParams делать. Сегодня используется search params, завтра json.stringify - лучше чтобы оно было внутри той функции. Можем просто объект с параметрами передавать

2024-11-08 13:49 UTC, ivan-podgornov commented on .github/workflows/pull-response-review.yml
> +      - submitted
давай это вынесем в pull-request-review и ифами будем разруливать какую джобу запускать, какую не запускать https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idif

2024-11-08 13:49 UTC, ivan-podgornov commented on .github/workflows/pull-response-review.yml
> +          -- --author ${{ github.actor }} \
вот эти первые два минуса давай на строчке выше оставим. В той второй джобе тоже так

2024-11-08 13:49 UTC, ivan-podgornov commented on packages/control-freak/send-telegram-request.ts
> +export async function sendTelegramRequest(url: string, params: URLSearchParams): Promise<void> {
url тоже в обоих случаях один и тот же. Можно оставить его в этой функции и не передавать в параметрах. Давай функцию переименуем на sendTelegramMessage вместе с файликом

2024-11-08 13:51 UTC, ivan-podgornov commented on .github/workflows/pull-response-review.yml
> +          npm exec control-freak response-review \
не хватает шага prepare-environment, из-за этого не отправляется сообщение

2024-11-08 15:47 UTC, ivan-podgornov requested changes

2024-11-08 15:47 UTC, ivan-podgornov commented on packages/control-freak/response-review.ts
> +  const message = `Уважаемый ${options.author} ответил на ревью у : ${options.reviewers}. PR: *${options.title}* - ${options.url}.`;
Нужно написать: "Уважаемый автор, твой пулл-реквест посмотрели ..."

2024-11-08 15:47 UTC, ivan-podgornov commented on .github/workflows/pull-request-review.yml
> +      - dismissed
Давай тут в зависимости от типа разные сообщения отправлять

2024-11-10 20:11 UTC, baronin reviewed
Жека кто там ?

2024-11-11 05:54 UTC, baronin reviewed
Где вы ?

2024-11-11 06:26 UTC, baronin reviewed
тест

2024-11-11 07:15 UTC, baronin reviewed
@ivan-podgornov родной, смотри

2024-11-12 08:07 UTC, ivan-podgornov submitted a review, later dismissed

2024-11-12 14:21 UTC, baronin reviewed
Иван, посмотри уважаемый

2024-11-12 15:19 UTC, baronin commented
да сколько можно

2024-11-12 15:33 UTC, ivan-podgornov submitted a review, later dismissed

2024-11-12 17:45 UTC, baronin commented
last

2024-11-12 18:04 UTC, baronin commented
прикол ?

2024-11-12 18:05 UTC, baronin reviewed
ну и ?

2024-11-12 18:53 UTC, baronin reviewed
и я

2024-11-12 20:44 UTC, ivan-podgornov requested changes

2024-11-12 20:44 UTC, ivan-podgornov commented on packages/control-freak/response-review.ts
> +  throw new Error('Неизвестный статус ревью');
заслуживает уважения. Грустно, что я сразу не увидел, может на switch переделаем?

2024-11-12 20:44 UTC, ivan-podgornov commented on packages/control-freak/types.ts
> +export interface ResponseReviewOptions extends Omit<ReviewOptions, 'reviewers'> {
Не, давай отдельно два объекта опишем. То что они похожи, не повод их переиспользовать. Появляется вероятность, что в ReviewOptions добавится поле, которое нужно для ResponseReviewOptions. Ну или если так делать, то нужны базовые опции, например BaseOptions и два которые их наследуют ReviewRequestOptions и ReviewResponseOptions

2024-11-12 20:44 UTC, ivan-podgornov commented on packages/control-freak/send-telegram-request.ts
> +): Promise<void> {
В options функция много лишнего принимает. Давай укажем что нужны только telegramBotToken и telegramChatId. Можем назвать это TelegramAuthOptions

2024-11-13 03:12 UTC, ivan-podgornov approved these changes

2024-11-13 03:12 UTC, ivan-podgornov commented on packages/control-freak/response-review.ts
> +  await sendTelegramRequest(message, {
Тут можно использовать authOptions и не создавать новый объект, поправим это в одном из следующих issue

2024-11-13 03:14 UTC, merged