fix: page-title
colibrijs/colibrijs pull request #164
Opened 2024-11-08 15:08 UTC by okovtkov

2024-11-12 08:35 UTC, ivan-podgornov requested changes

2024-11-12 08:35 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-table/screenshot-table.tsx
> +import type { TableColumnsType } from 'antd';
Немного такое себе целую библиотеку тянуть ради таблицы. Особенно плохо будет в тех репах, где antd изначально не было и появится только из-за скриншотных тестов.

2024-11-12 08:35 UTC, ivan-podgornov commented on packages/core/.storybook/screenshoter-config/get-approved-screenshots.ts
> +  const body = comments[0]?.body;
Если коментарий с апрувом будет идти вторым по счёту, то не сработает

2024-11-12 08:35 UTC, ivan-podgornov commented on packages/core/.storybook/screenshoter-config/get-approved-screenshots.ts
> +  const match = body!.match(/<pre id="screenshots-data">(.*?)<\/pre>/);
если добавить выше проверку

```ts
if (!body) {
  throw new Error('...');
}
```

то не нужен будет восклицательный знак

2024-11-12 08:35 UTC, ivan-podgornov commented on packages/core/.storybook/screenshoter-config/get-approved-screenshots.ts
> +  const text = match![1];
Ожидаешь что в match[1] будет некая строка. Если добавить проверку match, а потом и match[1] не нужны будут восклицательные знаки

2024-11-12 08:35 UTC, ivan-podgornov commented on packages/core/.storybook/screenshoter-config/screenshoter-config.ts
> +      (screenshot) => screenshot.name === story.name && screenshot.path === context.componentId
код проверки повторяется в панели и здесь. Давай вынесем в функцию

2024-11-12 16:34 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +            'approved-screenshots': JSON.stringify(storiesToApprove),
Добавь тут параметры null, 2 к JSON.stringify, чтоб нормально выглядело в пр'е

2024-11-12 17:21 UTC, okovtkov commented on packages/core/.storybook/screenshot-panel/screenshot-table/screenshot-table.tsx
> +import type { TableColumnsType } from 'antd';
https://github.com/colibrijs/colibrijs/issues/165 порешали

2024-11-13 00:27 UTC, ivan-podgornov submitted a review, later dismissed

2024-11-13 20:13 UTC, baronin submitted a review, later dismissed

2024-11-14 17:26 UTC, ivan-podgornov commented
Если есть хотя бы один апрувнутый тест, второй апрувнуть невозможно

<img width="759" alt="image" src="https://github.com/user-attachments/assets/e47e1dd8-460c-43a3-b1e9-31e7ac8c7b80">

2024-11-17 17:06 UTC, ivan-podgornov approved these changes

2024-11-17 17:08 UTC, merged