feat: компонент screenshot-comparator
colibrijs/colibrijs pull request #169
Opened 2024-11-28 12:57 UTC by okovtkov

2024-11-30 17:09 UTC, ivan-podgornov requested changes

2024-11-30 17:09 UTC, ivan-podgornov commented on eslint.config.js
> +  'packages/test-utils/**/*.{ts,tsx}',
Уже не актуально, надо убрать

2024-11-30 17:09 UTC, ivan-podgornov commented on package-lock.json
А выполнили ещë раз npm i

2024-11-30 17:09 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +        // eslint-disable-next-line react-hooks/rules-of-hooks -- так надо
Да не, не надо так. Вынеси панель в отдельный файлик. Этот явно слишком большим стал. Кнопку тогда тоже в отдельный файл

2024-11-30 17:09 UTC, ivan-podgornov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +        function onClick() {
Почему тут function, а не стрелочная функция?

2024-11-30 17:09 UTC, ivan-podgornov commented on packages/core/.storybook/screenshoter-config/get-approved-screenshots.ts
> +  if (!comments?.length) return [];
Что-то не то. В типах написанно что придëт массив, а тут появился optional chaining. Или типы врут, или chaining не нужен

2024-11-30 17:09 UTC, ivan-podgornov commented on packages/core/components/page-title/__stories__/screenshot/screenshot.stories.ts
> +export const ScreenshotTwo: Story = {
Удоли)

2024-11-30 17:09 UTC, ivan-podgornov commented on packages/core/package.json
> +    "@colibrijs/test-utils": "^1.0.0",
От пакета нужно избавиться

2024-11-30 17:09 UTC, ivan-podgornov commented on packages/test-utils/screenshots-comparator/decorator.tsx
> +    const isComparingScreenshots = useMemo(() => {
Тут незнание переменной не отражает еë суть

2024-12-01 00:12 UTC, okovtkov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +        function onClick() {
агрессирует на стрелочную. А начинаешь юзать хуки вроде useCallback, то тоже самое

2024-12-01 00:17 UTC, okovtkov commented on packages/test-utils/screenshots-comparator/decorator.tsx
> +    const isComparingScreenshots = useMemo(() => {
Не освобождает от ответственности ты хотел сказать

2024-12-01 13:53 UTC, okovtkov commented on packages/core/.storybook/screenshot-panel/screenshot-panel.tsx
> +        function onClick() {
Переделал на useCallback после того, как вынес в отдельный компонент

2024-12-01 19:24 UTC, ivan-podgornov requested changes

2024-12-01 19:24 UTC, ivan-podgornov commented on packages/core/.storybook/screenshots-comparator/screenshots-comparator.tsx
> +    return `${domain}${currentBranch}/storybook/screenshots/reference/${storyId}.png`;
Ну такое. Слишком сильно всё завязано на структуру файлов. Если чуть иначе выгрузить, то всё заруинится. Нужно чтоб при сборке сторибука указывалась ссылка на собранный сторибук и уже ею манипулировать

2024-12-01 19:24 UTC, ivan-podgornov commented on packages/core/.storybook/screenshots-comparator/decorator.tsx
> +    process.env.REACT_APP_REPOSITORY_SRC ?? 'https://github.com/colibrijs/colibrijs/';
Эта переменная и та которая на строчку выше, никогда никем не проставятся

2024-12-08 15:03 UTC, ivan-podgornov approved these changes

2024-12-08 15:57 UTC, merged