Issue 10
colibrijs/colibrijs pull request #26
Opened 2024-04-21 20:10 UTC by okovtkov

Resolve #10

2024-04-21 20:21 UTC, okovtkov commented on packages/core/components/props-editor/__stories__/props-editor.stories.tsx
> +  ],
вот подивис данную реализацию. Она явно неправильная. Это скорее всего надо вынести в отдельный файл куда-то, но я так и не понял куда

2024-04-21 22:32 UTC, ivan-podgornov commented on packages/core/components/props-editor/__stories__/props-editor.stories.tsx
> +  ],
правильно

2024-04-22 16:52 UTC, ivan-podgornov requested changes
Нужно тесты чуть переделать и ПР переименовать. Так чтоб не issue 10 назывался, а как название комита выглядел

2024-04-22 22:38 UTC, ivan-podgornov approved these changes

2024-04-22 22:44 UTC, merged